apiVersion: apps/v1
kind: Deployment
metadata:
  name: silexa-program-manager
  labels:
    app: silexa-program-manager
    silexa.component: program-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silexa-program-manager
  template:
    metadata:
      labels:
        app: silexa-program-manager
        silexa.component: program-manager
    spec:
      containers:
        - name: program-manager
          image: silexa/program-manager:local
          env:
            - name: MANAGER_URL
              value: http://silexa-manager:9090
            - name: PROGRAM_CONFIG_FILE
              value: /configs/programs/web_hosting.json
            - name: PROGRAM_RECONCILE_INTERVAL
              value: 30s
          volumeMounts:
            - name: configs
              mountPath: /configs
              readOnly: true
      volumes:
        - name: configs
          configMap:
            name: silexa-configs
            items:
              - key: programs-web_hosting.json
                path: programs/web_hosting.json
              - key: programs-releaseparty.json
                path: programs/releaseparty/releaseparty.json
