apiVersion: v1
kind: ServiceAccount
metadata:
  name: silexa-core
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: silexa-dyad
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: silexa-dyad
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: silexa-core
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: silexa-dyad
subjects:
  - kind: ServiceAccount
    name: silexa-dyad
roleRef:
  kind: Role
  name: silexa-dyad
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: silexa-core
subjects:
  - kind: ServiceAccount
    name: silexa-core
roleRef:
  kind: Role
  name: silexa-core
  apiGroup: rbac.authorization.k8s.io
