version: "3.9"

services:
  web:
    image: silexa/app-ReleaseParty-web:local
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "${APP_WEB_PORT:-3000}:3000"
    env_file:
      - ../../secrets/app-ReleaseParty.env

  backend:
    image: silexa/app-ReleaseParty-backend:local
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "${APP_BACKEND_PORT:-8080}:8080"
    env_file:
      - ../../secrets/app-ReleaseParty.env

networks:
  default:
    name: ${SILEXA_NETWORK:-silexa}
    external: true
