version: "3.9"

services:
  backend:
    image: silexa/app-ReleaseParty-backend:local
    environment:
      PORT: 8080
    ports:
      - "${APP_BACKEND_PORT:-8080}:8080"
    env_file:
      - ../../secrets/app-ReleaseParty.env

networks:
  default:
    name: ${SILEXA_NETWORK:-silexa}
    external: true
