apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictSecretRefs
metadata:
  name: silexa-dyad-secret-refs
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["silexa"]
    labelSelector:
      matchLabels:
        app: silexa-dyad
  parameters:
    allowedServiceAccounts:
      - silexa-credentials
